version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
    ports:
      - "3000:3000"

volumes:
  db_data:
